
package start;

import java.util.logging.Level;
import java.util.logging.Logger;
import page.objects.RegistrationPage;
import page.test.RegistPageTest;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import page.objects.LoginPage;
import page.objects.PostPage;
import page.test.LoginPageTest;
import page.test.PostPageTest;

/**
 *
 * @author stojmenovic
 */
public class GUI_Menu_Start extends javax.swing.JFrame {

	WebDriver driver = new ChromeDriver();

	/**
	 * Creates new form NewJFrame
	 */
	public GUI_Menu_Start() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")

	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jButton1 = new javax.swing.JButton();
		jButton3 = new javax.swing.JButton();
		jButton7 = new javax.swing.JButton();
		jButton5 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jButton4 = new javax.swing.JButton();
		jButton6 = new javax.swing.JButton();
		jButton8 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabel1.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
		jLabel1.setText("Automation Test for Website \"Izlet\"");

		jButton1.setText("Automated Registration Test");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jButton3.setText("Automated Login Test");
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});

		jButton7.setText(" Delete Post Test");
		jButton7.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton7ActionPerformed(evt);
			}
		});

		jButton5.setText(" Automated Post Creating");
		jButton5.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton5ActionPerformed(evt);
			}
		});

		jButton2.setText("Manual Registration Test");
		jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		jButton4.setText("Manual Login Test");
		jButton4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton4ActionPerformed(evt);
			}
		});

		jButton6.setText("Manual Post Creating");
		jButton6.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton6ActionPerformed(evt);
			}
		});

		jButton8.setText("Edit Post Test");
		jButton8.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				try {
					jButton8ActionPerformed(evt);
				} catch (InterruptedException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				layout.createSequentialGroup().addContainerGap().addGroup(layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
								layout.createSequentialGroup().addComponent(jLabel1).addGap(56, 56, 56))
						.addGroup(layout.createSequentialGroup().addGroup(layout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
												.addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING,
														javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
												.addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
										.addGap(24, 24, 24))
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
												.addComponent(jButton5, javax.swing.GroupLayout.Alignment.LEADING,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, 174,
														Short.MAX_VALUE))
										.addGap(25, 25, 25)))
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING,
												javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE))
								.addContainerGap()))));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup().addGap(28, 28, 28)
				.addComponent(
						jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
				.addGap(53, 53, 53)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jButton1)
						.addComponent(jButton2))
				.addGap(53, 53, 53)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jButton3)
						.addComponent(jButton4))
				.addGap(53, 53, 53)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jButton5)
						.addComponent(jButton6))
				.addGap(53, 53, 53)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jButton7)
						.addComponent(jButton8))
				.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		RegistrationPage.openPage(driver);
		try {
			RegistPageTest.fillForm(driver);
		} catch (Exception ex) {
			Logger.getLogger(GUI_Menu_Start.class.getName()).log(Level.SEVERE, null, ex);
		}
	}

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
		try {
			RegistrationPage.openPage(driver);
			LoginPageTest.fillForm(driver); // TODO add your handling code here:
		} catch (Exception ex) {
			Logger.getLogger(GUI_Menu_Start.class.getName()).log(Level.SEVERE, null, ex);
		}
	}

	private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {
		RegistrationPage.openPage(driver);
		LoginPage.SendKeysLogUsername(driver, "ivanst");
		LoginPage.SendKeysLogPassword(driver, "ivanst");
		LoginPage.getLoginButton(driver).click();
		PostPage.clickPostMenu(driver);
		PostPage.getPostDelete(driver).click();
	}

	private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {
		RegistrationPage.openPage(driver);
		LoginPage.SendKeysLogUsername(driver, "ivanst");
		LoginPage.SendKeysLogPassword(driver, "ivanst");
		LoginPage.getLoginButton(driver).click();
		try {
			PostPageTest.fillForm(driver); // TODO add your handling code here:
		} catch (Exception ex) {
			Logger.getLogger(GUI_Menu_Start.class.getName()).log(Level.SEVERE, null, ex);
		}
	}

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		try {
			RegistrationPage.openPage(driver);
			RegistPageTest.ScannerReg(driver);
		} catch (Exception ex) {
			Logger.getLogger(GUI_Menu_Start.class.getName()).log(Level.SEVERE, null, ex);
		}
	}

	private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
		try {
			RegistrationPage.openPage(driver);
			LoginPageTest.ScannerLog(driver); // TODO add your handling code here:
		} catch (Exception ex) {
			Logger.getLogger(GUI_Menu_Start.class.getName()).log(Level.SEVERE, null, ex);
		}
	}

	private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {
		try {
			RegistrationPage.openPage(driver);
			LoginPage.SendKeysLogUsername(driver, "ivanst");
			LoginPage.SendKeysLogPassword(driver, "ivanst");
			LoginPage.getLoginButton(driver).click();
			PostPageTest.ScannerPost(driver);
		} catch (Exception ex) {
			Logger.getLogger(GUI_Menu_Start.class.getName()).log(Level.SEVERE, null, ex);
		}
	}

	private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) throws InterruptedException {

		RegistrationPage.openPage(driver);
		LoginPage.SendKeysLogUsername(driver, "ivanst");
		LoginPage.SendKeysLogPassword(driver, "ivanst");
		LoginPage.getLoginButton(driver).click();
		PostPage.clickPostMenu(driver);
		PostPage.getPostEdit(driver).click();
		PostPage.clickEditText(driver);
		PostPage.SendKeysEditText(driver, "izmena");
		PostPage.clickEditSubButton(driver);

	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {

		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(GUI_Menu_Start.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(GUI_Menu_Start.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(GUI_Menu_Start.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(GUI_Menu_Start.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new GUI_Menu_Start().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JButton jButton5;
	private javax.swing.JButton jButton6;
	private javax.swing.JButton jButton7;
	private javax.swing.JButton jButton8;
	private javax.swing.JLabel jLabel1;
	// End of variables declaration
}
